language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run build:ci
after_success:
  - npm run cover:report
  - npm run report:codecov
  - npm run report:coveralls
  - npm run release
branches:
  only:
    - master
